/*
 * Bridge.app's native launcher for the development build.
 *
 * It runs Bridge's Python inside this process, so macOS sees "Bridge" (not Python.app)
 * when it asks for Accessibility, Microphone, Contacts and Calendar permission, and when it
 * lists the app in the Dock. bridge_paths.h (generated by app.desktop.bundle) defines
 * BRIDGE_PROJECT and BRIDGE_VENV_PYTHON. No credentials are compiled in.
 */
#include <Python.h>

#include <limits.h>
#include <mach-o/dyld.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "bridge_paths.h"

static void alert_and_exit(void) {
    system("/usr/bin/osascript -e 'display alert \"Bridge cannot start\" message "
           "\"Its Python environment or project folder moved. Rebuild the app with: "
           "python -m app.desktop.bundle --install --force\"' >/dev/null 2>&1");
    exit(1);
}

static void export_bundle_path(void) {
    char executable[PATH_MAX], resolved[PATH_MAX];
    uint32_t size = sizeof(executable);
    if (_NSGetExecutablePath(executable, &size) != 0 || realpath(executable, resolved) == NULL) {
        return;
    }
    /* .../Bridge.app/Contents/MacOS/Bridge → .../Bridge.app */
    for (int level = 0; level < 3; level++) {
        char *slash = strrchr(resolved, '/');
        if (slash == NULL) return;
        *slash = '\0';
    }
    setenv("BRIDGE_APP_BUNDLE", resolved, 1);
}

static void redirect_logs(void) {
    const char *home = getenv("HOME");
    if (home == NULL) return;
    char directory[PATH_MAX], log[PATH_MAX], previous[PATH_MAX];
    snprintf(directory, sizeof(directory), "%s/Library/Logs/Bridge", home);
    mkdir(directory, 0755);
    snprintf(log, sizeof(log), "%s/bridge.log", directory);
    snprintf(previous, sizeof(previous), "%s/bridge.log.1", directory);
    rename(log, previous); /* Keep the last run for diagnostics. */
    if (freopen(log, "a", stdout) != NULL) setvbuf(stdout, NULL, _IOLBF, 0);
    if (freopen(log, "a", stderr) != NULL) setvbuf(stderr, NULL, _IOLBF, 0);
}

int main(int argc, char *argv[]) {
    export_bundle_path();
    for (int index = 1; index < argc; index++) {
        if (strcmp(argv[index], "--login") == 0) setenv("BRIDGE_LAUNCHED_AT_LOGIN", "1", 1);
    }
    if (access(BRIDGE_VENV_PYTHON, X_OK) != 0 || chdir(BRIDGE_PROJECT) != 0) alert_and_exit();
    /* Lets Python find the project's virtual environment (pyvenv.cfg) and its packages. */
    setenv("PYTHONEXECUTABLE", BRIDGE_VENV_PYTHON, 1);
    redirect_logs();
    char *arguments[] = {"Bridge", "-m", "app.main", "--menubar", NULL};
    return Py_BytesMain(4, arguments);
}
